argo_manifests:
- name: "argocd operator"
  file: "argocd-operator.yaml.j2"
  post_wait:
    cmd: >-
      oc get crd
      gitopsservices.pipelines.openshift.io
      argocd.argoproj.io
    cond: "_resp.stdout == 0"
- name: "argocd instance"
  file: "argocd-config.yaml.j2"

repo_src_url: "ssh://git@github.com:florian-waldecker/openshift-bootcamp.git"
repo_pub_key: 
repo_priv_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  11111111111111111111111111111111111111111111111111111111111111
  11111111111111111111111111111111111111111111111111111111111111
  11111111111111111111111111111111111111111111111111111111111111
  11111111111111111111111111111111111111111111111111111111111111
  11111111111111111111111111111111111111111111111111111111111111
  11111111111111111111111111111111111111111111111111111111111111